#!/bin/bash

ROOT="/afs/cats.ucsc.edu/class"
CLASSES="cmps012a-pt.w16 cmps011-pt.w16"
ASG=$(basename $(pwd))
BIN="$ROOT/cmps012a-pt.w16/bin/$ASG"
SEPARATE="=================================================="

# Takes input cmd, runs it for every student
# Use this like follows: forall ls, forall echo "test"
forall() {
  for CLASS in $CLASSES; do
    CLASSNUM=$(echo $CLASS | cut -d '0' -f 2 | cut -d '-' -f 1)
    ASGDIR=$ROOT/$CLASS/$ASG
    cd $ASGDIR
    for STUDENT in $(ls -d */); do
      STUDENTDIR=$ASGDIR/$STUDENT
      cd $STUDENTDIR
      #echo "$SEPARATE"
      #echo "$CLASS/$STUDENT $@"
      $@
    done
  done
}

listfiles() {
  for FILE in *; do
    if [[ $FILE == errors || $FILE == *.dat ]]; then
      echo -n "($FILE)" " "
    else
      echo -n $FILE " "
    fi
  done
  echo
}
#forall listfiles

backup() {
  mkdir .backup
  cp * .backup
}
#forall backup

restore() {
  mkdir .trash
  mv * .trash
  cp .backup/* .
}
#forall restore

#forall ls -m > $BIN/current.ls
#forall ls -m .backup > $BIN/backup.ls

printerrors() {
  for FILE in *; do
    if [[ $FILE == *rror* && $FILE != *.dat ]]; then
      if [[ $FILE != errors ]]; then
        echo -n $FILE " "
      else
        echo -n "* "
      fi
    fi
  done
  #pwd
  echo
}

printnoerrors() {
  SWAG=false
  for FILE in *; do
    if [[ $FILE != *rror* && $FILE != *.dat ]]; then
      SWAG=true
      echo -n $FILE " "
    fi
  done
  echo
  if [[ $SWAG == true ]]; then pwd; fi
}
#forall printnoerrors

errordat() {
  if [[ -e errors.dat ]]; then
    pwd
  fi
}
#forall errordat

checkdat() {
  if ls -m | grep -q ".*.dat"; then
    if grep -Pq "4\s+[0-9]+" *.dat; then
      echo good " "
    else
      echo bad "  "
    fi
  else
    echo nofile
  fi
}
#forall checkdat

checkcomments() {
  FIRSTCHAR=$(head -c 1 errors.temp)
  if [[ $FIRSTCHAR == \# || $FIRSTCHAR == \/ || $FIRSTCHAR == - || $FIRSTCHAR == E || $FIRSTCHAR == e ]]; then
    echo "#SWAG"
  else
    echo "$SEPARATE"
    head -n 5 errors.temp
  fi
}
#forall checkcomments

checkerrors() {
  D=.d.errors.f
  FIX=.errorfix.f
  if [[ -e $D && ! -e $FIX ]]; then
    ERROR=$(cat $D)
    ERROR=${ERROR//\// \/ }
    ERROR=${ERROR// points - / | }
    echo $ERROR
    #touch $FIX
  fi
}
#forall checkerrors

haserrors() {
  D=.d.errors.f
  if [[ -e $D ]]; then
    echo "$STUDENT done"
  else
    echo "$STUDENT"
  fi
}
#forall haserrors

checkmail() {
  if [[ -e .mail.f ]]; then
    REMAIN=$((REMAIN + 1))
  fi
}
MAILING=true
while $MAILING; do
  REMAIN=0
  forall checkmail
  echo "$(date --rfc-3339=seconds): $REMAIN students remaining"
  if [[ $REMAIN = 0 ]]; then
    MAILING=false
  fi
  sleep 3
done

